import { productCopy } from './product-copy.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b=(label,action,attrs='')=>`<button type="button" class="button secondary" data-action="${action}" ${attrs}>${esc(label)}</button>`;
export const reviewScenarios=[['INITIAL','首次使用'],['MAIN_FLOW','正常流程'],['RECOGNITION_ERROR','时间需要修改'],['MISSING_INFORMATION','信息没听全'],['AI_FAILURE','暂时没整理好'],['SEND_FAILURE','消息没有发出去'],['PENDING_FAMILY','小梅还没回复'],['ACCEPTED','小梅可以陪同'],['DECLINED','小梅这次不能陪同'],['CHANGE_PROPOSED','小梅建议改时间'],['WITHDRAWN','已撤回陪同'],['CANCELLED','事情已取消'],['REMINDER_TRIGGER','提醒时间到了']];
const labels={'EL-TASK-03A':'整理内容已核对','EL-TASK-03B':'时间需要修改','EL-TASK-05':'修改后再次确认','EL-TASK-10':'办完后回到首页','FM-REQ-00':'还没有消息','FM-REQ-01':'有一件事等你回复','DM-01':'切换身份','DM-02':'快速查看','DM-03':'演示时间','DM-04A':'恢复初始状态确认','DM-04B':'恢复初始状态结果'};
export function renderReviewTools(state,catalog=[]) {
 const view=state.currentView,toolId=state.catalogScreenId?.startsWith('DM-')?state.catalogScreenId:view==='RESET_CONFIRM'?'DM-04A':view==='RESET_RESULT'?'DM-04B':'DM-02';
 const reset=view==='RESET_CONFIRM'?`<section data-review-group="reset" role="alert"><h3>恢复初始状态？</h3><p>清空这份浏览器中的家庭关系、事情和请求，时间恢复到10月6日20:00。</p>${b('确认恢复初始状态','reset')}${b('继续查看','demo')}</section>`:view==='RESET_RESULT'?`<section data-review-group="reset" role="status"><h3>已恢复初始状态</h3><p>可以重新开始。</p>${b('重新开始','elder-home')}</section>`:'';
 return `<aside class="review-tools" data-review-screen-id="${toolId}" aria-label="评审辅助"><h2>评审辅助</h2><p>用于快速查看不同演示情况，不属于正式产品功能。语音、消息和提醒为预置演示状态。</p>${reset}<section data-review-group="identity"><h3>当前身份：${state.currentRole==='FAMILY'?'小梅':'张阿姨'}</h3>${b('切换到张阿姨','role-elder')}${b('切换到小梅','role-family')}<a href="/" class="review-link">打开张阿姨的独立产品</a><a href="/family" class="review-link">打开小梅的独立产品</a></section><section data-review-group="scenarios"><h3>快速查看</h3><div class="scenario-grid">${reviewScenarios.map(([id,label])=>b(label,'load-demo-scenario',`data-scenario="${id}"`)).join('')}</div></section><section class="review-time" data-review-group="time"><h3>演示时间</h3><p>${esc(new Date(state.demoClock).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}))}</p>${b('查看提醒时间到了','review-reminder',state.task.status!=='CONFIRMED'?'disabled':'')}${b('查看小梅暂未回复','review-no-response',state.collaborationRequest.status!=='PENDING'?'disabled':'')}${view==='TASK_PROCESSING'?b('继续整理，查看结果','finish-parsing'):''}${view==='REQUEST_SENDING'?b('继续发送，查看结果','finish-sending'):''}</section><details class="screen-index"><summary>查看全部画面</summary>${catalog.map(item=>b((labels[item.id]||productCopy[item.id].title)+(item.id.startsWith('FM-')?' · 小梅':item.id.startsWith('DM-')?' · 辅助工具':' · 张阿姨'),'load-screen',`data-screen="${item.id}"`)).join('')}</details>${b('恢复初始状态','ask-reset')}</aside>`;
}
